spring:
  application:
    name: kairos
  datasource:
    url: ${POSTGRES_URL:jdbc:postgresql://localhost:5432/postgres}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
grpc:
  client:
    tenshi:
      address: tenshi-grpc.ardyc.ru
      negotiation-type: tls
      security:
        trust-cert-collection: ${SSL_CERT_PATH:classpath:root_ca.crt}